Request to join the Feature branch to the Main branch as part of performing the Bubble Sort algorithm relative to the first Microverse Ruby project.
aristides1000/Advanced_Building_Blocks_Bubble_Sort pull request #1
Opened 2021-04-01 17:34 UTC by aristides1000

Request to join the Feature branch in the Main branch as part of the realization of the Bubble Sort algorithm relative to the first Microverse Ruby project, In this project I learned the importance of element ordering algorithms in arrays, in this case In particular I made use of the Bubble Sort methodology

2021-04-01 19:48 UTC, enaburekhan requested changes
# Status: Changes required:full_moon:.
**Hi Molina!
Great job on your first ruby project:clap::clap:.**

**Major Highlights**

- The PR and readme is very descriptive
- The codebase is clean and the written methods are easy to read and understand.

However, we just need to make a few changes to get the project approved:muscle:.

**To improve**
- [x] As highlighted the PR below. Refactor the bubble_sort_by method to use yield. And pay attention to what's been yielded.  the test is failing because `bubble_sort_by is suppose to raises an error if block is not given`.  A local jump error was expected, but nothing was raised. Kindly fix this.

- [x] Also, correct the highlighted line 34 in the readme to reflect the current project. Which is `bubble_sort in ruby`.

Make the above-required changes and when you are ready, request another review.
Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

2021-04-01 19:48 UTC, enaburekhan commented on README.md
> +- [Grab the index.html file and open it on your favorite browser.](https://helpdeskgeek.com/how-to/open-an-html-file-in-google-chrome/)
Kindly correct this line to reflect the current project which is `bubble_sort `using the `ruby` language.

2021-04-01 19:48 UTC, enaburekhan commented on bubble_sort.rb
> +end
bubble_sort_by raises an error if block is not given. expected `LocalJumpError` but nothing was raised. You need to refactor the method to use `yield`.

2021-04-02 02:22 UTC, aristides1000 commented
Thank you very much for the corrections, I fixed my bubble_sort.rb file and my README.md file, according to the indications given in the previous correction.

2021-04-02 07:49 UTC, DeliceLydia approved these changes
# Status: Approved ![image](https://user-images.githubusercontent.com/44745855/113394021-d3577100-9397-11eb-89d3-55a737fa3129.png)

Congratulations @aristides1000 for implementing changes requested by the previous TSE and this project shows that you really worked hard and your bubble_sort is running perfectly now

## Kudos once again and feel free to merge and move on 

N.B: next time try to make a title of your PR short and descriptive

All the best,

Lydia Ingabire

2021-04-02 09:31 UTC, merged